[package]
name = "advent-rs-2022"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common" }
indoc = "1.0"
itertools = "0.10"
regex = "1"